#Save this file without the _template in the name:
# config.yaml will be called in this directory
#Way of working 
###############################################################
#     from imodulator.Config import config_instance            
#     # Get access to imported modules
#     nn = config_instance.get_nextnanopy()
#     lumapi = config_instance.get_lumapi()
#     InGaAsP_models = config_instance.get_ingaasp_models()
###############################################################
#Paths that involves other package locations
lumerical_api: 
  path: "C:/Program Files/Lumerical/v232/api/python/lumapi.py"

nextnano:
  nextnano++:
    exe: "C:/Program Files/nextnano/2024_12_20/nextnano++/bin/nextnano++_Intel_64bit.exe"
    license: "C:/Users/20235351/OneDrive - TU Eindhoven/Documents/nextnano/License/License_nnp.lic"
    database: "C:/Program Files/nextnano/2024_12_20/nextnano++/database/database_nnp.in"
    output: "D:/Repos/imodulator/tests"
  # You can add other nextnano variants here if needed
  # nextnano3:
  #   exe: "path/to/nextnano3.exe"
  #   license: "path/to/license.lic"
  #   database: "path/to/database.in"